development:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydevelopmentdb
  host: localhost
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb
  host: localhost
  pool: 5
  timeout: 5000
